import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime, timedelta
import sys
sys.path.append('../..')

from src.loaders.database import DatabaseManager
from src.config.settings import settings

st.set_page_config(page_title="Alerts Dashboard", page_icon="🚨", layout="wide")

# Initialize
@st.cache_resource
def get_database():
    return DatabaseManager()

db = get_database()

st.title("🚨 Trading Alerts Dashboard")
st.markdown("Monitor and manage your trading alerts in real-time")

# Sidebar - Filters
st.sidebar.header("🔍 Filters")

date_filter = st.sidebar.selectbox(
    "Time Period",
    ["Today", "Last 7 Days", "Last 30 Days", "All Time"],
    index=1
)

# Alert types
alert_types = [
    "RSI_OVERSOLD", 
    "RSI_OVERBOUGHT", 
    "GOLDEN_CROSS", 
    "DEATH_CROSS",
    "MACD_BULLISH_CROSSOVER", 
    "MACD_BEARISH_CROSSOVER", 
    "PRICE_SURGE", 
    "PRICE_DROP"
]

alert_type_filter = st.sidebar.multiselect(
    "Alert Types",
    alert_types,
    default=["RSI_OVERSOLD", "RSI_OVERBOUGHT", "GOLDEN_CROSS"]
)

# Stock filter
stock_filter = st.sidebar.multiselect(
    "Filter by Stocks",
    options=settings.NIFTY_50_STOCKS,
    default=[]
)

# Load alerts data
@st.cache_data(ttl=60)
def load_alerts(days=None):
    if days == 0:  # Today
        query = """
            SELECT * FROM alerts 
            WHERE DATE(triggered_at) = CURRENT_DATE
            ORDER BY triggered_at DESC
        """
    elif days:
        query = f"""
            SELECT * FROM alerts 
            WHERE triggered_at >= NOW() - INTERVAL '{days} days'
            ORDER BY triggered_at DESC
        """
    else:  # All time
        query = "SELECT * FROM alerts ORDER BY triggered_at DESC"
    
    try:
        return pd.read_sql(query, db.engine)
    except Exception as e:
        st.error(f"Error loading alerts: {str(e)}")
        return pd.DataFrame()

# Determine days for filter
days_map = {
    "Today": 0,
    "Last 7 Days": 7,
    "Last 30 Days": 30,
    "All Time": None
}
days = days_map[date_filter]

alerts_df = load_alerts(days)

if alerts_df.empty:
    st.info("📭 No alerts found for the selected period.")
    st.markdown("---")
    st.subheader("ℹ️ About Trading Alerts")
    st.markdown("""
    This dashboard displays trading alerts generated by the pipeline. Alerts are triggered when:
    
    - **RSI Oversold/Overbought:** RSI indicator crosses threshold levels
    - **Golden/Death Cross:** Moving average crossovers
    - **MACD Crossovers:** MACD line crosses signal line
    - **Price Surge/Drop:** Significant price movements
    
    Run the pipeline to generate alerts: `python scripts/initial_data_load.py`
    """)
    st.stop()

# Apply filters
if alert_type_filter:
    alerts_df = alerts_df[alerts_df['alert_type'].isin(alert_type_filter)]

if stock_filter:
    alerts_df = alerts_df[alerts_df['symbol'].isin(stock_filter)]

if alerts_df.empty:
    st.info("📭 No alerts match your filter criteria.")
    st.stop()

# Summary Metrics
st.subheader("📊 Alert Summary")

col1, col2, col3, col4 = st.columns(4)

with col1:
    total_alerts = len(alerts_df)
    st.metric("Total Alerts", total_alerts)

with col2:
    unique_stocks = alerts_df['symbol'].nunique()
    st.metric("Unique Stocks", unique_stocks)

with col3:
    sent_alerts = alerts_df[alerts_df['is_sent'] == True].shape[0] if 'is_sent' in alerts_df.columns else 0
    st.metric("Sent Alerts", sent_alerts)

with col4:
    pending_alerts = alerts_df[alerts_df['is_sent'] == False].shape[0] if 'is_sent' in alerts_df.columns else 0
    st.metric("Pending Alerts", pending_alerts)

# Alert Distribution
st.markdown("---")
col1, col2 = st.columns(2)

with col1:
    st.subheader("📈 Alerts by Type")
    
    alert_type_counts = alerts_df['alert_type'].value_counts()
    
    fig = px.bar(
        x=alert_type_counts.values,
        y=alert_type_counts.index,
        orientation='h',
        labels={'x': 'Count', 'y': 'Alert Type'},
        color=alert_type_counts.values,
        color_continuous_scale='Viridis',
        text=alert_type_counts.values
    )
    fig.update_traces(textposition='outside')
    fig.update_layout(
        showlegend=False, 
        height=400,
        xaxis_title="Number of Alerts",
        yaxis_title="Alert Type"
    )
    st.plotly_chart(fig, use_container_width=True)

with col2:
    st.subheader("🏢 Top 10 Stocks by Alerts")
    
    stock_counts = alerts_df['symbol'].value_counts().head(10)
    
    fig = px.pie(
        values=stock_counts.values,
        names=stock_counts.index,
        title=''
    )
    fig.update_traces(textposition='inside', textinfo='percent+label')
    fig.update_layout(height=400)
    st.plotly_chart(fig, use_container_width=True)

# Alert Timeline
st.markdown("---")
st.subheader("📅 Alert Timeline")

alerts_df['date'] = pd.to_datetime(alerts_df['triggered_at']).dt.date
daily_alerts = alerts_df.groupby('date').size().reset_index(name='count')

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=daily_alerts['date'],
    y=daily_alerts['count'],
    mode='lines+markers',
    name='Daily Alerts',
    line=dict(color='#1f77b4', width=2),
    marker=dict(size=8),
    fill='tozeroy'
))

fig.update_layout(
    title='Alert Frequency Over Time',
    xaxis_title='Date',
    yaxis_title='Number of Alerts',
    hovermode='x unified',
    height=400
)

st.plotly_chart(fig, use_container_width=True)

# Recent Alerts
st.markdown("---")
st.subheader("🔔 Recent Alerts")

# Define alert type information
alert_info = {
    'RSI_OVERSOLD': {'emoji': '🟢', 'color': 'success', 'label': 'Oversold', 'action': 'BUY'},
    'RSI_OVERBOUGHT': {'emoji': '🔴', 'color': 'error', 'label': 'Overbought', 'action': 'SELL'},
    'GOLDEN_CROSS': {'emoji': '⭐', 'color': 'success', 'label': 'Bullish', 'action': 'BUY'},
    'DEATH_CROSS': {'emoji': '💀', 'color': 'error', 'label': 'Bearish', 'action': 'SELL'},
    'MACD_BULLISH_CROSSOVER': {'emoji': '📈', 'color': 'success', 'label': 'Buy Signal', 'action': 'BUY'},
    'MACD_BEARISH_CROSSOVER': {'emoji': '📉', 'color': 'warning', 'label': 'Sell Signal', 'action': 'SELL'},
    'PRICE_SURGE': {'emoji': '🚀', 'color': 'success', 'label': 'Surge', 'action': 'WATCH'},
    'PRICE_DROP': {'emoji': '⚠️', 'color': 'error', 'label': 'Drop', 'action': 'WATCH'},
}

# Pagination
alerts_per_page = 10
total_pages = (len(alerts_df) - 1) // alerts_per_page + 1

if 'page' not in st.session_state:
    st.session_state.page = 0

col1, col2, col3 = st.columns([1, 2, 1])

with col1:
    if st.button("⬅️ Previous", disabled=st.session_state.page == 0):
        st.session_state.page -= 1
        st.rerun()

with col2:
    st.markdown(f"<h4 style='text-align: center'>Page {st.session_state.page + 1} of {total_pages}</h4>", 
                unsafe_allow_html=True)

with col3:
    if st.button("Next ➡️", disabled=st.session_state.page >= total_pages - 1):
        st.session_state.page += 1
        st.rerun()

# Display alerts for current page
start_idx = st.session_state.page * alerts_per_page
end_idx = start_idx + alerts_per_page
page_alerts = alerts_df.iloc[start_idx:end_idx]

for idx, alert in page_alerts.iterrows():
    info = alert_info.get(alert['alert_type'], {'emoji': '📌', 'color': 'info', 'label': 'Alert', 'action': 'MONITOR'})
    
    with st.container():
        col1, col2, col3, col4, col5 = st.columns([1, 2, 2, 3, 2])
        
        with col1:
            st.markdown(f"### {info['emoji']}")
        
        with col2:
            st.markdown(f"**{alert['symbol']}**")
            st.caption(f"Action: {info['action']}")
        
        with col3:
            if info['color'] == 'success':
                st.success(info['label'])
            elif info['color'] == 'error':
                st.error(info['label'])
            elif info['color'] == 'warning':
                st.warning(info['label'])
            else:
                st.info(info['label'])
        
        with col4:
            st.text(alert['condition_met'])
            st.caption(f"Value: {float(alert['value']):.2f}")
        
        with col5:
            timestamp = pd.to_datetime(alert['triggered_at'])
            st.text(timestamp.strftime('%Y-%m-%d'))
            st.text(timestamp.strftime('%H:%M:%S'))
            
            if 'is_sent' in alert and alert['is_sent']:
                st.caption("✅ Notified")
            else:
                st.caption("⏳ Pending")
        
        st.markdown("---")

# Alert Statistics
st.markdown("---")
st.subheader("📊 Alert Statistics")

col1, col2, col3 = st.columns(3)

with col1:
    st.write("**Most Active Stocks**")
    top_stocks = alerts_df['symbol'].value_counts().head(5)
    
    for stock, count in top_stocks.items():
        percentage = (count / len(alerts_df)) * 100
        st.metric(stock, f"{count} alerts", f"{percentage:.1f}%")

with col2:
    st.write("**Alert Type Distribution**")
    alert_type_counts = alerts_df['alert_type'].value_counts()
    
    for alert_type in alert_type_counts.head(5).index:
        count = alert_type_counts[alert_type]
        percentage = (count / len(alerts_df)) * 100
        label = alert_type.replace('_', ' ').title()
        st.metric(label, count, f"{percentage:.1f}%")

with col3:
    st.write("**Recent Activity**")
    
    # Today
    today = datetime.now().date()
    today_alerts = len(alerts_df[alerts_df['date'] == today])
    st.metric("Today", today_alerts)
    
    # Yesterday
    yesterday = today - timedelta(days=1)
    yesterday_alerts = len(alerts_df[alerts_df['date'] == yesterday])
    change = today_alerts - yesterday_alerts
    st.metric("Yesterday", yesterday_alerts, f"{change:+d}")
    
    # This week
    week_start = today - timedelta(days=today.weekday())
    week_alerts = len(alerts_df[alerts_df['date'] >= week_start])
    st.metric("This Week", week_alerts)

# Detailed Alert Table
st.markdown("---")
st.subheader("📋 Detailed Alert History")

# Format display dataframe
display_df = alerts_df.copy()
display_df['triggered_at'] = pd.to_datetime(display_df['triggered_at']).dt.strftime('%Y-%m-%d %H:%M:%S')
display_df['value'] = display_df['value'].round(2)

if 'is_sent' in display_df.columns:
    display_df['status'] = display_df['is_sent'].apply(lambda x: '✅ Sent' if x else '⏳ Pending')
    display_cols = ['symbol', 'alert_type', 'condition_met', 'value', 'triggered_at', 'status']
else:
    display_cols = ['symbol', 'alert_type', 'condition_met', 'value', 'triggered_at']

# Styling function
def highlight_alert_type(row):
    alert_type = row['alert_type']
    if 'OVERSOLD' in alert_type or 'GOLDEN' in alert_type or 'BULLISH' in alert_type:
        return ['background-color: #d4edda'] * len(row)
    elif 'OVERBOUGHT' in alert_type or 'DEATH' in alert_type or 'BEARISH' in alert_type:
        return ['background-color: #f8d7da'] * len(row)
    else:
        return ['background-color: #fff3cd'] * len(row)

styled_df = display_df[display_cols].head(50).style.apply(highlight_alert_type, axis=1)

st.dataframe(styled_df, use_container_width=True, height=400)

# Export and Management
st.markdown("---")
col1, col2, col3 = st.columns(3)

with col1:
    # Export alerts
    csv = alerts_df.to_csv(index=False)
    st.download_button(
        label="📥 Export Alerts as CSV",
        data=csv,
        file_name=f"alerts_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
        mime="text/csv",
        use_container_width=True
    )

with col2:
    # Mark all as read
    if st.button("✅ Mark All as Sent", type="secondary", use_container_width=True):
        try:
            update_query = "UPDATE alerts SET is_sent = TRUE WHERE is_sent = FALSE"
            db.engine.execute(update_query)
            st.success("All alerts marked as sent!")
            st.rerun()
        except Exception as e:
            st.error(f"Error: {str(e)}")

with col3:
    # Clear old alerts
    if st.button("🗑️ Clear Old Alerts (30+ days)", type="secondary", use_container_width=True):
        if 'confirm_clear' not in st.session_state:
            st.session_state['confirm_clear'] = False
        
        if st.session_state['confirm_clear']:
            try:
                delete_query = "DELETE FROM alerts WHERE triggered_at < NOW() - INTERVAL '30 days'"
                result = db.engine.execute(delete_query)
                st.success(f"Cleared old alerts!")
                st.session_state['confirm_clear'] = False
                st.rerun()
            except Exception as e:
                st.error(f"Error: {str(e)}")
        else:
            st.session_state['confirm_clear'] = True
            st.warning("⚠️ Click again to confirm")

# Alert Configuration Info
st.markdown("---")
st.subheader("⚙️ Alert Configuration")

with st.expander("ℹ️ View Current Alert Thresholds"):
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("""
        **RSI Thresholds:**
        - Oversold: < 30
        - Overbought: > 70
        
        **Price Change:**
        - Threshold: ±5%
        """)
    
    with col2:
        st.markdown("""
        **Volume:**
        - Spike: 2x average
        
        **Moving Averages:**
        - Golden Cross: SMA50 > SMA200
        - Death Cross: SMA50 < SMA200
        """)
    
    st.info("""
    **To modify thresholds:** Edit the `.env` file in your project root:
    ```
    RSI_OVERSOLD=30
    RSI_OVERBOUGHT=70
    PRICE_CHANGE_THRESHOLD=5.0
    VOLUME_SPIKE_MULTIPLIER=2.0
    ```
    Then restart the application.
    """)

# Alert Types Reference
with st.expander("📖 Alert Types Reference"):
    st.markdown("""
    | Alert Type | Description | Action |
    |------------|-------------|--------|
    | **RSI Oversold** | RSI below 30 | Consider buying - stock may be undervalued |
    | **RSI Overbought** | RSI above 70 | Consider selling - stock may be overvalued |
    | **Golden Cross** | SMA50 crosses above SMA200 | Bullish signal - uptrend starting |
    | **Death Cross** | SMA50 crosses below SMA200 | Bearish signal - downtrend starting |
    | **MACD Bullish** | MACD crosses above signal line | Buy signal - momentum turning positive |
    | **MACD Bearish** | MACD crosses below signal line | Sell signal - momentum turning negative |
    | **Price Surge** | Price increase > 5% | High volatility - monitor closely |
    | **Price Drop** | Price decrease > 5% | High volatility - monitor closely |
    """)

# Refresh button
st.markdown("---")
if st.button("🔄 Refresh Alerts", type="primary", use_container_width=True):
    st.cache_data.clear()
    st.rerun()

# Footer
st.markdown("---")
st.caption(f"Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
st.caption("💡 Tip: Alerts are generated automatically when the Airflow pipeline runs daily at 6 PM")